#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,2,3,10,43&i=15,16,17&v=27,26,25 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define myoptions_
#define DSP_MODEL DSP_SSD1305
// #define DSP_HSPI			true
// 4-wire SPI pins (your custom wiring)
// #define TFT_MOSI              13    // DIN  → GPIO11
// #define TFT_SCK               14    // CLK  → GPIO10
#define TFT_CS                46    // CS   → GPIO12
#define TFT_DC                9    // DC   → GPIO13
#define TFT_RES               10

#define I2S_DOUT 1
#define I2S_BCLK 2
#define I2S_LRC 42

#define BTN_LEFT 15
#define BTN_CENTER 16
#define BTN_RIGHT 17

#endif
