#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,2,3,10,43&i=15,16,17&v=27,26,25 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define myoptions_h
#define DSP_MODEL DSP_SSD1306
#define I2C_SDA 13
#define I2C_SCL 12

#define I2S_DOUT 4
#define I2S_BCLK 6
#define I2S_LRC 5

#define BTN_LEFT 7
#define BTN_CENTER 8
#define BTN_RIGHT 9

#endif
